---
title: "index"
author: "camila franco"
format:
  html: 
   toc: true
lang: es
---

# Este documento presenta datos recuperados del [sitio de datos abiertos del Organismo de Investigación Judicial (OIJ)](https://sitiooij.poder-judicial.go.cr/index.php/ayuda/servicios-policiales/servicios-a-organizaciones/indice-de-transparencia-del-sector-publico-costarricense/datos-abiertos)

# Carga y muestra de los datos
```{r}
#| label: carga-muestra-datos
#| echo: false
delitos_2022 <- read.csv("estadsticaspoliciales2022.csv")

# Tabla con las 10 primeras filas y con columnas seleccionadas
knitr::kable(
	head(
		delitos_2022[, c("Delito", "Fecha", "Victima", "Edad", "Provincia")], 
		10
	),
	caption = "Muestra de datos de delitos cometidos en 2022 en Costa Rica"
)
```

# graficos de delitos por provincia

## barras verticales
```{r}
#| label: delitps-provincia-barras-verticales
#| code-fold: true

barplot (height = table(delitos_2022$Provincia))
```

## barras horizontales 

```{r}
#| label: cantidad-delitos-provincia-barras-horizontales
#| code-fold: true
#| 
# Crear tabla de frecuencias
tabla_delitos <- table(delitos_2022$Provincia)

# Ordenar ascendentemente la tabla de frecuencia
tabla_delitos_ordenada <- sort(tabla_delitos)

# Gráfico de barras horizontales
barplot(
	height = tabla_delitos_ordenada,
	main = "Cantidad de delitos cometidos en 2022 por provincia", 
	sub = "Fuente: OIJ",
	col = "red",
	las = 2,
	cex.names = 0.5,
	cex.axis = 0.7,
	horiz = TRUE
)
```

# pastel

```{r}
#| label: cantidad-delitos-provincia-pastel
#| code-fold: true


tabla_delitos <- table(delitos_2022$Provincia)

tabla_delitos_ordenada <- sort(tabla_delitos)

pie(
  tabla_delitos_ordenada,
  main = "Cantidad de delitos cometidos en 2022 por provincia",
  sub = "Fuente: OIJ",
  col = rainbow(length(tabla_delitos_ordenada)),
  cex = 0.8,
  labels = paste0(
  	round(100 * tabla_delitos_ordenada / sum(tabla_delitos_ordenada), 1), 
  	"%"
  )
)

legend(
  "topright",
  legend = names(tabla_delitos_ordenada),
  fill = rainbow(length(tabla_delitos_ordenada)),
  cex = 0.8,
  bty = "n" # quitar el marco de la leyenda, valor = ("n", "o")
)

```

